#!/usr/bin/env python

# Tento soubor byl automaticky vygenerován pomocí predictor_generator.py

import pandas as pd
from sklearn.model_selection import train_test_split
{model_imp}
from sklearn.metrics import log_loss, accuracy_score

pd.set_option("future.no_silent_downcasting", True)


data = pd.read_csv("{csv_soubor}")



# Začátek vloženého úseku pro úpravu dat ještě před predikcí.

{vlozeny_usek}

# Konec vloženého úseku




X_all = data[{X_all_cols}]
y_all = data[{y_all_cols}]

X_train, X_test, y_train, y_test = train_test_split(
    X_all, 
    y_all,
    random_state=1,
    test_size={test_size_frac})

print('Velikost trenovaci mnoziny:', len(X_train))
print('Velikost testovaci mnoziny:', len(X_test))

model = {model}
model.fit(X_train, y_train)
y_pred_loss = model.predict_proba(X_test)
y_pred_acc = model.predict(X_test)

print ("ACCURACY:", accuracy_score(y_test, y_pred_acc))
print ("LOSS:", log_loss(y_test, y_pred_loss))
